Todo_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo_app/', include('todo_app.urls')),
    path('admin/', admin.site.urls),
]

todo_app/urls.py
from django.urls import path
from .views import Main, Input, Complete, DeleteItem

app_name = 'todo_app'

urlpatterns = [
    path("", Main.as_view(), name='Top'),
    path('delete/<int:item_id>/', DeleteItem.as_view(), name='Delete'),
    path('input/', Input.as_view(), name='Input'),
    path('complete/', Complete.as_view(), name='Complete')
]

todo_app/models.py
from django.db import models
import datetime

# Create your models here.
class TodoModel(models.Model):
    Todo = models.TextField()
    DeadLine = models.DateField(default=datetime.date.today)
    Category_Choices = (
        ('work', '仕事'),
        ('study', '勉強'),
        ('hobby', '趣味'),
        ('others', 'その他'),
    )
    Category = models.CharField(max_length=10, choices=Category_Choices, blank=True)

todo_app/forms.py
from django import forms
from .models import TodoModel

class InputForm(forms.ModelForm):
    #ToDo = forms.CharField(widget=forms.Textarea(attrs={'class':'textarea', 'placeholder':'ToDoを入力'}))
    #DeadLine = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'date'}))
    class Meta:
        model = TodoModel
        fields = ['Todo', 'DeadLine', 'Category']
        widgets = {
            'Todo': forms.Textarea(attrs={'class': 'textarea', 'placeholder': 'ToDoを入力'}),
            'DeadLine': forms.DateInput(attrs={'type': 'date', 'class': 'date'}),
            'Category' : forms.Select(attrs={'class': 'Category'})
        }
        labels = {
            'Todo': 'ToDo',  # ToDoフィールドのラベルを変更
            'DeadLine': '期限',  # DeadLineフィールドのラベルを変更
            'Category': 'カテゴリ',  # Categoryフィールドのラベルを変更
        }

todo_app/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import InputForm
from .models import TodoModel
import datetime

# Create your views here.
class Main(View):
    def get(self, request):
        data = TodoModel.objects.all().order_by('DeadLine')
        return render(request, "todo_app/main.html", {'data' : data})

class DeleteItem(View):
    def post(self, request, item_id):
        item = TodoModel.objects.get(id=item_id)
        item.delete()
        return redirect('/todo_app/')

class Input(View):
    def get(self, request):
        form = InputForm()
        return render(request, "todo_app/input.html", {'form':form})

    def post(self, request):
        form = InputForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/todo_app/complete/')
        else:
            form = InputForm()
        return render(request, 'todo_app/input.html', {'form':form})

class Complete(View):
    def get(self, request):
        return render(request, "todo_app/complete.html")

todo_app/templates/todoApp/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo登録完了</title>
</head>
<body>
    <p>Todo登録が完了しました</p>
    <a href="{% url 'todoApp:Top' %}">トップ画面へ</a>
</body>
</html>

todo_app/templates/todoApp/input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>インプット画面</p>
    <form method = "post" action="{% url 'todoApp:Input' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">登録</button>
    </form>
    <a href="{% url 'todoApp:Top' %}">戻る</a>
</body>
</html>

todo_app/templates/todoApp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'todoApp/main.css' %}">
    <title>現在のToDo</title>
</head>
<body>
    <p class = "Title">ToDoリスト</p>
    <div class = "Wrapper">
        {% for item in data %}
        <div class = "Card">
            <p>ToDo: {{ item.Todo }}</p>
            <p>締切: {{ item.DeadLine }}</p>
            <form method="post" action="{% url 'todoApp:Delete' item.id %}">
                {% csrf_token %}
                <button>完了</button>
            </form>
        </div>
        {% endfor %}
    </div>
    <a href="{% url 'todoApp:Input' %}" class = "Link">ToDoを作成する</a>
</body>
</html>

todo_app/templates/todo_app/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'todo_app/complete.css' %}">
    <title>ToDo登録完了</title>
</head>
<body>
    <div class= "main">
        <p class = "subTitle">Todo登録が完了しました</p>
    </div>
    <a href="{% url 'todo_app:Top' %}" class = "back">トップ画面へ</a>
</body>
</html>

todo_app/templates/todo_app/input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'todo_app/input.css' %}">
    <title>ToDo追加ページ</title>
</head>
<body>
    <p class="explain">ToDoを追加</p>
    <div class = "main">
        <form method = "post" action="{% url 'todo_app:Input' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="submit">登録</button>
        </form>
    </div>
    <a href="{% url 'todo_app:Top' %}" class="back">戻る</a>
</body>
</html>

todo_app/templates/todo_app/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'todo_app/main.css' %}">
    <title>現在のToDo</title>
</head>
<body>
    <p class = "Title">ToDoリスト</p>
    <div class = "flex-box">
        <div class = "left-container">

        </div>
        <div class = "main">
            <ul class="stack01">
                {% if data %}
                    {% for item in data %}
                    <li class = "Card">
                        <p class="ToDo">{{ item.Todo }}</p>
                        <p>締切: {{ item.DeadLine|date:"n月j日" }}</p>
                        <p>カテゴリ:{{ item.get_Category_display }}</p>
                        <form method="post" action="{% url 'todo_app:Delete' item.id %}">
                            {% csrf_token %}
                            <button class = "Complete">完了</button>
                        </form>
                    </li>
                    {% endfor %}
                {% else %}
                    <p>ToDoはありません</p>
                {% endif %}
            </ul>
        </div>
        <div class = "right-container">

        </div>
    </div>
    <div class = "footer">
        <a href="{% url 'todo_app:Input' %}" class = "Link">ToDoを追加する</a>
    </div>
</body>
</html>